name: Check Tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      SOLC_SWITCH_GITHUB_TOKEN: ${{ secrets.SOLC_SWITCH_GITHUB_TOKEN }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Checkout submodules
        run: make submodules
        
      - name: Run Tests
        run: |
          make test